name: Sync NODE Clients

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to NODE-HTLeamington
        run: |
          git config --global user.email "nixinxcom@users.noreply.github.com"
          git config --global user.name "nixinxcom"
          git remote add node-htleamington https://nixinxcom:${{ secrets.NODES_SYNC_TOKEN }}@github.com/nixinxcom/NODE-HTLeamington.git
          git push node-htleamington main --force

      - name: Push to NODE-HTWindsor
        run: |
          git remote add node-htwindsor https://nixinxcom:${{ secrets.NODES_SYNC_TOKEN }}@github.com/nixinxcom/NODE-HTWindsor.git
          git push node-htwindsor main --force

      - name: Push to NODE-ElPatron
        run: |
          git remote add node-elpatron https://nixinxcom:${{ secrets.NODES_SYNC_TOKEN }}@github.com/nixinxcom/NODE-ElPatron.git
          git push node-elpatron main --force
