name: Sync NODE repos and deploy

on:
  push:
    branches:
      - main

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (completo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura Git
        run: |
          git config --global user.email "nixinxcom@users.noreply.github.com"
          git config --global user.name "nixinxcom"

      - name: Push to NODE-HTLeamington
        env:
          PAT: ${{ secrets.NODES_SYNC_TOKEN }}
        run: |
          git remote add node-htleamington https://nixinxcom:${PAT}@github.com/nixinxcom/NODE-HTLeamington.git
          git push node-htleamington HEAD:main --force

      - name: Push to NODE-HTWindsor
        env:
          PAT: ${{ secrets.NODES_SYNC_TOKEN }}
        run: |
          git remote add node-htwindsor https://nixinxcom:${PAT}@github.com/nixinxcom/NODE-HTWindsor.git
          git push node-htwindsor HEAD:main --force

      - name: Push to NODE-ElPatron
        env:
          PAT: ${{ secrets.NODES_SYNC_TOKEN }}
        run: |
          git remote add node-elpatron https://nixinxcom:${PAT}@github.com/nixinxcom/NODE-ElPatron.git
          git push node-elpatron HEAD:main --force
