name: Sync NODE repos and deploy

on:
  push:
    branches:
      - main

jobs:
  sync-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror push to NODE-HTLeamington
        run: |
          git clone --mirror https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NIXINX.git
          cd NIXINX.git
          git remote add target https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NODE-HTLeamington.git
          git push --mirror target

      - name: Mirror push to NODE-HTWindsor
        run: |
          git clone --mirror https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NIXINX.git
          cd NIXINX.git
          git remote add target https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NODE-HTWindsor.git
          git push --mirror target

      - name: Mirror push to NODE-ElPatron
        run: |
          git clone --mirror https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NIXINX.git
          cd NIXINX.git
          git remote add target https://x-access-token:${{ secrets.PAT }}@github.com/nixinxcom/NODE-ElPatron.git
          git push --mirror target
